package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"

	"gopkg.in/yaml.v3"
)

// Config holds all configuration settings for the CLI
type Config struct {
	// Authentication (from env or config file)
	MapsToken      string `yaml:"maps_token,omitempty"`
	TeamID         string `yaml:"team_id,omitempty"`
	KeyID          string `yaml:"key_id,omitempty"`
	PrivateKey     string `yaml:"private_key,omitempty"`
	PrivateKeyPath string `yaml:"private_key_path,omitempty"`

	// Snapshot defaults
	DefaultZoom    int    `yaml:"default_zoom,omitempty"`
	DefaultSize    string `yaml:"default_size,omitempty"`
	DefaultFormat  string `yaml:"default_format,omitempty"`
	DefaultMapType string `yaml:"default_map_type,omitempty"`

	// Search defaults
	DefaultLimit    int    `yaml:"default_limit,omitempty"`
	DefaultCategory string `yaml:"default_category,omitempty"`

	// API settings
	BaseURL string `yaml:"base_url,omitempty"`
}

// DefaultConfig returns a Config with sensible defaults
func DefaultConfig() *Config {
	return &Config{
		DefaultZoom:    14,
		DefaultSize:    "800x600",
		DefaultFormat:  "png",
		DefaultMapType: "standard",
		DefaultLimit:   10,
		BaseURL:        "https://maps-api.apple.com",
	}
}

// Load reads configuration from file and merges with defaults
// Order of precedence: Flags > Environment > Config File > Defaults
func Load() (*Config, error) {
	// Start with defaults
	cfg := DefaultConfig()

	// Load from config file if it exists
	if err := cfg.loadFromFile(); err != nil {
		// Non-fatal: just log and continue with defaults
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("loading config file: %w", err)
		}
	}

	// Merge environment variables (they override config file)
	cfg.loadFromEnv()

	return cfg, nil
}

// loadFromFile reads the config file from the user's config directory
func (c *Config) loadFromFile() error {
	path, err := ConfigFilePath()
	if err != nil {
		return err
	}

	// Path is safely constructed from os.UserConfigDir() via ConfigFilePath()
	// and is not user-controlled, so path traversal is not possible.
	// #nosec G304 - Config file path is safely constructed
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	if err := yaml.Unmarshal(data, c); err != nil {
		return fmt.Errorf("parsing config file: %w", err)
	}

	return nil
}

// loadFromEnv loads configuration from environment variables
func (c *Config) loadFromEnv() {
	if v := os.Getenv("AMS_MAPS_TOKEN"); v != "" {
		c.MapsToken = v
	}
	if v := os.Getenv("AMS_TEAM_ID"); v != "" {
		c.TeamID = v
	}
	if v := os.Getenv("AMS_KEY_ID"); v != "" {
		c.KeyID = v
	}
	if v := os.Getenv("AMS_PRIVATE_KEY"); v != "" {
		c.PrivateKey = v
	}
	if v := os.Getenv("AMS_PRIVATE_KEY_PATH"); v != "" {
		c.PrivateKeyPath = v
	}
	if v := os.Getenv("AMS_BASE_URL"); v != "" {
		c.BaseURL = v
	}
}

// Save writes the current configuration to the config file
func (c *Config) Save() error {
	path, err := ConfigFilePath()
	if err != nil {
		return err
	}

	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}

	// Marshal to YAML
	data, err := yaml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	// Write with header
	content := "# Apple Map Server CLI Configuration\n" +
		"# This file is automatically generated. Edit with: ams config set <key> <value>\n\n" +
		string(data)

	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("writing config file: %w", err)
	}

	return nil
}

// ConfigFilePath returns the path to the config file
func ConfigFilePath() (string, error) {
	configDir, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("getting user config directory: %w", err)
	}

	return filepath.Join(configDir, "ams", "config.yaml"), nil
}

// ConfigDir returns the config directory path
func ConfigDir() (string, error) {
	configDir, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("getting user config directory: %w", err)
	}

	return filepath.Join(configDir, "ams"), nil
}

// Set updates a configuration value by key
func (c *Config) Set(key, value string) error {
	switch key {
	case "maps_token":
		c.MapsToken = value
	case "team_id":
		c.TeamID = value
	case "key_id":
		c.KeyID = value
	case "private_key":
		c.PrivateKey = value
	case "private_key_path":
		c.PrivateKeyPath = value
	case "default_zoom":
		zoom, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid zoom value: %w", err)
		}
		c.DefaultZoom = zoom
	case "default_size":
		c.DefaultSize = value
	case "default_format":
		c.DefaultFormat = value
	case "default_map_type":
		c.DefaultMapType = value
	case "default_limit":
		limit, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid limit value: %w", err)
		}
		c.DefaultLimit = limit
	case "default_category":
		c.DefaultCategory = value
	case "base_url":
		c.BaseURL = value
	default:
		return fmt.Errorf("unknown config key: %s", key)
	}

	return nil
}

// Get retrieves a configuration value by key
func (c *Config) Get(key string) (string, error) {
	switch key {
	case "maps_token":
		return c.MapsToken, nil
	case "team_id":
		return c.TeamID, nil
	case "key_id":
		return c.KeyID, nil
	case "private_key":
		return c.PrivateKey, nil
	case "private_key_path":
		return c.PrivateKeyPath, nil
	case "default_zoom":
		return strconv.Itoa(c.DefaultZoom), nil
	case "default_size":
		return c.DefaultSize, nil
	case "default_format":
		return c.DefaultFormat, nil
	case "default_map_type":
		return c.DefaultMapType, nil
	case "default_limit":
		return strconv.Itoa(c.DefaultLimit), nil
	case "default_category":
		return c.DefaultCategory, nil
	case "base_url":
		return c.BaseURL, nil
	default:
		return "", fmt.Errorf("unknown config key: %s", key)
	}
}

// List returns all configuration keys and values
func (c *Config) List() map[string]string {
	return map[string]string{
		"maps_token":       c.MapsToken,
		"team_id":          c.TeamID,
		"key_id":           c.KeyID,
		"private_key":      c.PrivateKey,
		"private_key_path": c.PrivateKeyPath,
		"default_zoom":     strconv.Itoa(c.DefaultZoom),
		"default_size":     c.DefaultSize,
		"default_format":   c.DefaultFormat,
		"default_map_type": c.DefaultMapType,
		"default_limit":    strconv.Itoa(c.DefaultLimit),
		"default_category": c.DefaultCategory,
		"base_url":         c.BaseURL,
	}
}
